include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/l10n/app_localizations.dart
    - lib/l10n/app_localizations_*.dart

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - always_declare_return_types
    - prefer_typing_uninitialized_variables
    - prefer_relative_imports
    - prefer_single_quotes
    - unawaited_futures
